INSERT INTO `discipline` (`id_discipline`, `nom_discipline`) VALUES
(2, 'Agronomie'),
(3, 'Anthropologie'),
(4, 'Arts'),
(5, 'Astronomie'),
(6, 'Biologie'),
(7, 'Chimie'),
(8, 'Communications'),
(9, 'Droit'),
(10, 'Économie'),
(11, 'Éducation'),
(14, 'Environnement'),
(15, 'Génie (sciences de l''ingénieur)'),
(18, 'Géographie'),
(19, 'Géologie'),
(21, 'Gestion'),
(22, 'Histoire'),
(23, 'Informatique'),
(24, 'Linguistique'),
(25, 'Littératures'),
(26, 'Mathématiques'),
(27, 'Médecine'),
(28, 'Océanographie'),
(29, 'Philosophie'),
(30, 'Physique'),
(31, 'Politique'),
(32, 'Psychologie'),
(33, 'Sociologie'),
(34, 'Télécommunications'),
(35, 'Religions'),
(36, 'Administration publique'),
(37, 'Agro-alimentaire'),
(38, 'Aménagement du territoire'),
(39, 'Archéologie'),
(40, 'Architecture'),
(41, 'Biotechnologies'),
(42, 'Commerce'),
(43, 'Criminologie'),
(44, 'Démographie'),
(45, 'Écologie'),
(46, 'Foresterie'),
(47, 'Hydrologie'),
(48, 'Langues'),
(49, 'Médecine vétérinaire'),
(50, 'Santé'),
(51, 'Sciences de l''information'),
(52, 'Statistiques'),
(53, 'Télédétection'),
(54, 'Tourisme'),
(55, 'Traduction'),
(56, 'Travail social');

